[package]
name = "kassensystem"
version = "0.1.0"
authors = ["Christian Schäl <christian@tuta.io>"]

[dependencies]
sqlite3 = "0.24"
tiny_http = "0.6.0"
tera = "0.11"
lazy_static = "1.1.0"
url = "1.7.1"
serde = "1.0"
serde_derive = "1.0"
base64 = "0.10.0"
percent-encoding = "1.0.1"
